# Generated by Django 4.2.4 on 2024-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
