# Generated by Django 4.2.4 on 2024-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_kyc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
