# Generated by Django 4.2.4 on 2024-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_has_kyc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
