# Generated by Django 4.2.4 on 2024-08-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsettings',
            name='can_deposit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='can_transfer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tradingsettings',
            name='can_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
